package com.bettingproject.sofascorelocal.domain.provider;

public enum J3CircuitReason {
    NONE,
    STARTUP_LOCK,
    OPERATOR_STOP,
    QUALIFICATION_TERMINAL_LOCK,
    MANUAL_COLLECTION_TERMINAL_LOCK,
    HTTP_BAD_REQUEST,
    HTTP_UNAUTHORIZED,
    HTTP_FORBIDDEN,
    ENDPOINT_UNAVAILABLE,
    HTTP_TOO_MANY_REQUESTS,
    TIMEOUT,
    TRANSPORT_IO_FAILURE,
    PAYLOAD_TOO_LARGE,
    SENSITIVE_CONTENT_REJECTED,
    UNEXPECTED_CONTENT,
    SCHEMA_INCOMPATIBLE,
    SERVER_ERROR
}
