package com.bettingproject.sofascorelocal.domain.provider;

public enum J3NetworkBlockReason {
    NONE,
    FEATURE_DISABLED,
    GLOBAL_STOP_ACTIVE,
    ENDPOINT_NOT_ALLOWED,
    ENDPOINT_NOT_CONFIGURED,
    OPERATOR_ACTIVATION_REQUIRED,
    MANUAL_CONFIRMATION_REQUIRED,
    CACHE_AVAILABLE,
    CIRCUIT_LOCKED,
    CIRCUIT_OPEN,
    CALL_ALREADY_IN_PROGRESS,
    MINIMUM_DELAY_NOT_ELAPSED
}
