package com.bettingproject.sofascorelocal.application.network;

public enum J3ManualCallControlError {
    GLOBAL_STOP_ALREADY_CLEARED,
    GLOBAL_STOP_ACTIVE,
    CIRCUIT_ALREADY_ACTIVATED,
    CIRCUIT_NOT_CLOSED,
    ACTIVE_INTENT_ALREADY_EXISTS,
    NO_PENDING_INTENT,
    REQUEST_ID_MISMATCH,
    CONFIRMATION_EXPIRED,
    ACKNOWLEDGEMENT_REQUIRED,
    CONFIRMATION_TEXT_MISMATCH,
    INTENT_ALREADY_CONFIRMED
}
