package com.bettingproject.sofascorelocal.application.network;

public enum J3ManualCallControlError {
    GLOBAL_STOP_ALREADY_CLEARED,
    GLOBAL_STOP_ACTIVE,
    CIRCUIT_ALREADY_ACTIVATED,
    CIRCUIT_NOT_CLOSED,
    ACTIVE_INTENT_ALREADY_EXISTS,
    NO_PENDING_INTENT,
    REQUEST_ID_MISMATCH,
    CONFIRMATION_EXPIRED,
    ACKNOWLEDGEMENT_REQUIRED,
    CONFIRMATION_TEXT_MISMATCH,
    INTENT_ALREADY_CONFIRMED,
    PROVIDER_TRANSPORT_UNAVAILABLE,
    INTENT_NOT_READY,
    EXECUTION_ALREADY_STARTED,
    EXECUTION_NOT_ACTIVE,
    PAGE_SEQUENCE_INVALID,
    QUALIFICATION_ALREADY_CONSUMED,
    DATE_NOT_AUTHORIZED
}
