package com.bettingproject.sofascorelocal.application.network;

public enum J4RealPhase1ControlError {
    PROVIDER_TRANSPORT_UNAVAILABLE,
    ACTIVE_CAMPAIGN_EXISTS,
    NO_PENDING_CAMPAIGN,
    REQUEST_ID_MISMATCH,
    CONFIRMATION_EXPIRED,
    ACKNOWLEDGEMENT_REQUIRED,
    CONFIRMATION_TEXT_MISMATCH,
    EXECUTION_NOT_ACTIVE,
    EVENT_SEQUENCE_INVALID
}
