package com.bettingproject.sofascorelocal.application.network;

public enum J5RealControlError {
    PROVIDER_TRANSPORT_UNAVAILABLE,
    EVENT_ID_NOT_ALLOWED,
    EVENT_ID_MISMATCH,
    ACTIVE_CAMPAIGN_EXISTS,
    TERMINAL_LOCK_REQUIRES_RESTART,
    NO_PENDING_CAMPAIGN,
    REQUEST_ID_MISMATCH,
    CONFIRMATION_EXPIRED,
    ACKNOWLEDGEMENT_REQUIRED,
    CONFIRMATION_TEXT_MISMATCH,
    EXECUTION_NOT_ACTIVE,
    ENDPOINT_ORDER_INVALID,
    ENDPOINT_ALREADY_COMPLETED
}
