package com.bettingproject.sofascorelocal.application.network;

public enum TournamentEventDiscoveryControlError {
    PROVIDER_TRANSPORT_UNAVAILABLE,
    ACTIVE_REQUEST_EXISTS,
    TERMINAL_LOCK_REQUIRES_RESTART,
    CATALOG_UNAVAILABLE,
    TOURNAMENT_SELECTION_NOT_ALLOWED,
    CATALOG_CHANGED,
    CATALOG_REVALIDATION_ERROR,
    NO_PENDING_REQUEST,
    REQUEST_ID_MISMATCH,
    CONFIRMATION_EXPIRED,
    ACKNOWLEDGEMENT_REQUIRED,
    CONFIRMATION_TEXT_MISMATCH,
    EXECUTION_NOT_ACTIVE
}
