spring:
  config:
    activate:
      on-profile: local
  thymeleaf:
    cache: false

sofascore:
  playwright:
    request-timeout: ${SOFASCORE_PLAYWRIGHT_REQUEST_TIMEOUT:20s}

logging:
  level:
    org.flywaydb: INFO
    org.hibernate.SQL: WARN
