package com.bettingproject.sofascorelocal.domain.export;

public enum J7ExportError {
    EVENT_NOT_FOUND,
    EXPORT_NOT_FOUND,
    CANDIDATE_ALREADY_PENDING,
    IDENTICAL_EXPORT_ALREADY_VALIDATED,
    INVALID_CONFIRMATION,
    INVALID_REJECTION_REASON,
    INVALID_SCHEMA,
    SENSITIVE_CONTENT,
    FILE_TOO_LARGE,
    INCOHERENT_SOURCE,
    INVALID_HASH,
    IDENTITY_MISMATCH,
    SOURCE_SET_CHANGED,
    INVALID_TRANSITION,
    FILE_TAMPERED,
    NOT_DOWNLOADABLE,
    STORAGE_UNAVAILABLE,
    DATABASE_UNAVAILABLE
}
