package com.bettingproject.sofascorelocal.domain.delivery;

/**
 * Safe, value-free error codes for the optional J7 delivery domain.
 */
public enum J7DeliveryError {
    INVALID_EXPORT_ID,
    INVALID_REMOTE_IMPORT_ID,
    INVALID_FILE_SHA256,
    INVALID_DATA_SHA256,
    INVALID_PROTOCOL_VERSION,
    INVALID_ACKNOWLEDGEMENT_STATUS,
    INVALID_ACKNOWLEDGEMENT,
    ACKNOWLEDGEMENT_TOO_LARGE,
    INVALID_RECEIVED_AT,
    INVALID_PAYLOAD_SIZE,
    ACKNOWLEDGEMENT_MISMATCH,
    INVALID_TRANSITION,
    DELIVERY_DISABLED,
    DELIVERY_IN_PROGRESS,
    DELIVERY_RUNTIME_POISONED,
    EXECUTION_MODE_MISMATCH,
    REMOTE_DELIVERY_NOT_AUTHORIZED,
    OFFICIAL_PERMISSION_NOT_EVIDENCED,
    RECEIVER_NOT_QUALIFIED,
    SENDER_NOT_QUALIFIED,
    INVALID_RECEIVER_ORIGIN,
    MTLS_CERTIFICATE_NOT_CONFIGURED,
    PAYLOAD_PROVENANCE_NOT_ELIGIBLE,
    PAYLOAD_IDENTITY_CHANGED,
    PROVIDER_OWNER_GO_REQUIRED,
    AUTOMATIC_RETRY_NOT_ALLOWED,
    LOOPBACK_QUALIFICATION_DISABLED,
    INVALID_LOOPBACK_ORIGIN,
    INVALID_CONFIRMATION,
    CONFIRMATION_NOT_PREPARED,
    CONFIRMATION_EXPIRED,
    CONFIRMATION_ALREADY_USED,
    RECONCILIATION_NOT_ALLOWED,
    TRANSPORT_CONFIGURATION_FAILED,
    TRANSPORT_CLEANUP_FAILED
}
