package com.bettingproject.sofascorelocal.domain.delivery;

/**
 * Safe, value-free error codes for the optional J7 delivery domain.
 */
public enum J7DeliveryError {
    INVALID_EXPORT_ID,
    INVALID_REMOTE_IMPORT_ID,
    INVALID_FILE_SHA256,
    INVALID_DATA_SHA256,
    INVALID_PROTOCOL_VERSION,
    INVALID_ACKNOWLEDGEMENT_STATUS,
    INVALID_ACKNOWLEDGEMENT,
    ACKNOWLEDGEMENT_TOO_LARGE,
    INVALID_RECEIVED_AT,
    INVALID_PAYLOAD_SIZE,
    ACKNOWLEDGEMENT_MISMATCH,
    INVALID_TRANSITION,
    DELIVERY_DISABLED,
    REMOTE_DELIVERY_NOT_AUTHORIZED,
    OFFICIAL_PERMISSION_NOT_EVIDENCED,
    LOOPBACK_QUALIFICATION_DISABLED,
    INVALID_LOOPBACK_ORIGIN,
    INVALID_CONFIRMATION
}
