package com.bettingproject.sofascorelocal.application.event;

public enum J5OfflineBatchError {
    OFFLINE_POLICY_UNAVAILABLE,
    INVALID_SELECTION,
    EVENT_NOT_FOUND,
    ACTIVE_BATCH_EXISTS,
    NO_PENDING_BATCH,
    REQUEST_ID_MISMATCH,
    CONFIRMATION_EXPIRED,
    ACKNOWLEDGEMENT_REQUIRED,
    CONFIRMATION_TEXT_MISMATCH,
    PLAN_CHANGED,
    FILE_NAME_INVALID,
    DUPLICATE_FILE,
    FILE_SET_MISMATCH,
    EMPTY_PAYLOAD,
    PAYLOAD_TOO_LARGE,
    BATCH_TOO_LARGE,
    MULTIPART_LIMIT_EXCEEDED,
    SENSITIVE_CONTENT,
    STATISTICS_PAYLOAD_INCOMPATIBLE,
    INCIDENTS_PAYLOAD_INCOMPATIBLE,
    LINEUPS_PAYLOAD_INCOMPATIBLE,
    OPERATOR_STOP,
    STORAGE_UNAVAILABLE,
    LOCAL_EXECUTION_FAILURE
}
